controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    use_sim_time: true

    # Add these timeout parameters
    controller_manager_timeout: 10.0
    activate_controllers_timeout: 10.0

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - link1_to_base
      - servo_horn_to_servo
      - camera_roll
      - camera_pitch
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    # Add timeout for trajectory execution
    action_server_timeout: 10.0

ackermann_steering_controller:
  ros__parameters:
    # must match test config
    rear_wheels_names:
      - rear_left_wheel_joint
      - rear_right_wheel_joint
    front_wheels_names:
      - front_left_steering_joint
      - front_right_steering_joint

    # Required kinematics (must be > 0)
    wheelbase: 1.2
    front_wheel_track: 0.8
    rear_wheel_track: 0.8
    front_wheels_radius: 0.3
    rear_wheels_radius: 0.3

    # Controller options
    open_loop: false
    position_feedback: true
    use_stamped_vel: true
    velocity_rolling_window_size: 5
    publish_rate: 50.0
    cmd_vel_timeout: 0.5
