amcl:
  ros__parameters:
    use_sim_time: true
    use_map_topic: true
    odom_frame_id: "odom"
    base_frame_id: "body_link"
    # ^ for ekf node 

planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["SmacPlannerHybrid"]
    SmacPlannerHybrid:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      motion_model_for_search: "DUBIN"
      minimum_turning_radius: 1.0   # adjust to your robot

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_plugins: ["RegulatedPurePursuit"]
    RegulatedPurePursuit:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 1.0
      lookahead_dist: 1.0
      use_velocity_scaled_lookahead_dist: true

bt_navigator:
  ros__parameters:
    use_sim_time: true

waypoint_follower:
  ros__parameters:
    use_sim_time: true

